[config]
# Je kunt kiezen uit 'dynamic', 'monochrome', 'neutral', etc.
palette = "dynamic" 

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/matugen-colors.rasi'

[templates.quickshell]
input_path = '~/.config/matugen/templates/QuickshellColors.qml'
output_path = '~/.config/quickshell/Colors.qml'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland_colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/color.toml'