-- ==============================================================================
--  Hyprland config (Lua)
--  Colors are from colors.conf - generated by matugen
--  Adjust terminal and browser to your preference
-- ==============================================================================

local colors_path = os.getenv("HOME") .. "/.config/hypr/colors.lua"
local colors = {
  primary   = "ffb0d0ff",
  secondary = "e1bdc9ff",
  tertiary  = "191114ff",
  surface   = "191114ff",
  background= "191114ff",
  foreground= "ffffffcc",
}

-- Probeer matugen bestand te laden, val terug op fallback bij error/missing
local ok, loaded = pcall(loadfile, colors_path)
if ok and loaded then
  local loaded_colors = loaded()
  if loaded_colors then colors = loaded_colors end
end

-- 2. Globale Hyprland kleuren (worden pas ingesteld na laden)
col.active_border = {colors.primary, colors.secondary, 45}
col.inactive_border = {colors.surface, 0.8}
col.background = colors.background
col.foreground = colors.foreground


-- -- Monitor -------------------------------------------------------------------
-- preferred = use native resolution of the screen
hl.monitor("", "preferred", "auto", 1)

-- -- Programs ------------------------------------------------------------------
local terminal    = "alacritty"
local menu        = "rofi -show run"
local browser     = "vivaldi"
local musicplayer = "spotify-launcher"
local onlinechat  = "discord"
local filemanager = "dolphin"
local codeeditor  = "vscodium-wayland"
local pcbeditor   = "kicad"
local d3design    = "freecad"

-- -- Autostart -----------------------------------------------------------------
-- Resolve environment variables for Lua paths
local data_home = os.getenv("XDG_DATA_HOME") or (os.getenv("HOME") .. "/.local/share")

hl.exec_once(data_home .. "/quickshell-dotfiles/scripts/backgroundSwicher/init_wallpaper.sh")
hl.exec_once("qs")
hl.exec_once(browser)
hl.exec_once(musicplayer)
hl.exec_once(onlinechat)

hl.exec_once("wl-paste --type text --watch cliphist store")
hl.exec_once("wl-paste --type image --watch cliphist store")
hl.exec_once("wl-clip-persist --clipboard regular")

-- -- Environment Variables -----------------------------------------------------
hl.env("XCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- -- Setup (Input, General, Decoration, etc.) ----------------------------------
hl.setup({
    input = {
        kb_layout = "us",
        numlock_by_default = true,
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = false,
            disable_while_typing = true,
        }
    },
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 2,
        layout = "dwindle",
        allow_tearing = false,
    },
    decoration = {
        rounding = 8,
        blur = {
            enabled = true,
            size = 4,
            passes = 1,
            vibrancy = 0.1696,
        }
    },
    animations = {
        enabled = false,
    },
    dwindle = {
        preserve_split = true,
    }
})

-- -- Window Rules --------------------------------------------------------------
hl.window_rule({
    match = { class = "my-window" },
    border_size = 10
})

hl.window_rule({
    match = { class = musicplayer },
    workspace = "9 silent"
})

hl.window_rule({
    match = { class = onlinechat },
    workspace = "9 silent"
})

-- ==============================================================================
--  Keybindings
-- ==============================================================================

local mod = "SUPER"

-- -- Launch Programs -----------------------------------------------------------
hl.bind(mod, "Return", "exec", terminal)
hl.bind(mod, "Space",  "exec", menu)
hl.bind(mod, "E",      "exec", browser)
hl.bind(mod, "L",      "exec", musicplayer)
hl.bind(mod, "I",      "exec", onlinechat)
hl.bind(mod, "F",      "exec", filemanager)
hl.bind(mod, "C",      "exec", codeeditor)
hl.bind(mod, "P",      "exec", pcbeditor)
hl.bind(mod, "O",      "exec", d3design)

-- Clipboard GUI
hl.bind(mod, "V", "exec", "cliphist list | rofi -dmenu | cliphist decode | wl-copy")

-- Screenshot tools (Piped commands wrapped in sh -c for Lua exec to parse correctly)
hl.bind("",      "Print", "exec", 'sh -c "hyprshot -m region --raw --freeze | satty --filename -"')
hl.bind("SHIFT", "Print", "exec", 'sh -c "hyprshot -m active --raw | satty --filename -"')

-- -- Window Management ---------------------------------------------------------
hl.bind(mod, "Q", "killactive")
hl.bind(mod, "A", "fullscreen")
hl.bind(mod, "S", "togglefloating")
hl.bind(mod, "U", "pseudo") -- dwindle
hl.bind(mod, "J", "layoutmsg", "togglesplit") -- dwindle

-- -- Move Focus (Arrow keys) ---------------------------------------------------
hl.bind(mod, "left",  "movefocus", "l")
hl.bind(mod, "right", "movefocus", "r")
hl.bind(mod, "up",    "movefocus", "u")
hl.bind(mod, "down",  "movefocus", "d")

-- -- Move Windows --------------------------------------------------------------
hl.bind(mod .. " SHIFT", "left",  "movewindow", "l")
hl.bind(mod .. " SHIFT", "right", "movewindow", "r")
hl.bind(mod .. " SHIFT", "up",    "movewindow", "u")
hl.bind(mod .. " SHIFT", "down",  "movewindow", "d")

-- -- Workspaces 1-9 (Using a loop for clean code) ------------------------------
for i = 1, 9 do
    local key = tostring(i)
    -- Switch to workspace
    hl.bind(mod, key, "workspace", key)
    -- Send window to workspace
    hl.bind(mod .. " SHIFT", key, "movetoworkspace", key)
end

-- -- Scroll Workspaces with Mouse Wheel ----------------------------------------
hl.bind(mod, "mouse_down", "workspace", "e+1")
hl.bind(mod, "mouse_up",   "workspace", "e-1")

-- -- Mouse Binds (Move & Resize) -----------------------------------------------
hl.bindm(mod, "mouse:272", "movewindow")
hl.bindm(mod, "mouse:273", "resizewindow")

-- -- Audio Binds (pipewire + wireplumber) --------------------------------------
hl.bind("", "XF86AudioRaiseVolume", "exec", "wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+")
hl.bind("", "XF86AudioLowerVolume", "exec", "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-")
hl.bind("", "XF86AudioMute",        "exec", "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle")
hl.bind("", "XF86AudioMicMute",     "exec", "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle")

-- -- Brightness Binds (brightnessctl) ------------------------------------------
hl.bind("", "XF86MonBrightnessUp",   "exec", "brightnessctl set 5%+")
hl.bind("", "XF86MonBrightnessDown", "exec", "brightnessctl set 5%-")

-- -- Exit Hyprland -------------------------------------------------------------
hl.bind(mod .. " SHIFT", "L", "exit")