# ~/.config/matugen/templates/hyprland.conf
general {
    col.active_border = rgba({{colors.primary.default.hex}}ff) rgba({{colors.secondary.default.hex}}ff) 45deg
    col.inactive_border = rgba({{colors.surface.default.hex}}aa)
}

group {
    col.border_active = rgba({{colors.primary.default.hex}}ff)
    col.border_inactive = rgba({{colors.surface.default.hex}}aa)
}